#!/usr/bin/env python3

import json
import pprint
import sys

file1 = sys.argv[1]
file2 = sys.argv[2]

def main():
    lines1 = read_file(file1)
    lines2 = read_file(file2)
    compare_lists_of_dicts(lines1, lines2)

def compare_lists_of_dicts(l1,l2):
    errors = False
    if len(l1) != len(l2):
        raise AssertionError("expected lists to be of same length")
    for counter, _ in enumerate(l1):
        try:
            assert l1[counter] == l2[counter]
        except AssertionError:
            print(f"expected\n\n\n{pprint.pformat(l1[counter])} \n\n\nto equal\n\n\n {pprint.pformat(l2[counter])}")
            errors = True
    
    if errors:
        raise AssertionError

def read_file(filename):
    with open(filename) as f:
        lines = [json.loads(line) for line in f.readlines()]
    for line in lines:
        # host is generated by logstash, and will change run to run
        del(line['host'])
    lines.sort(key=lambda x: x['message'])
    return lines

if __name__ == "__main__":
    main()
